version: '3.8'
services:
  api:
    build: .
    environment:
      API_KEY: ${API_KEY}
      MODEL_DIR: ${MODEL_DIR:-models/t5-finetuned}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: >
      uvicorn scripts.run_inference_api:app
      --host 0.0.0.0 --port 8000
