# Training configuration template for model fine-tuning
model_name_or_path: t5-small
dataset_dir: data/processed/dataset
output_dir: models/t5-finetuned
batch_size: 8
epochs: 3
learning_rate: 5e-5
max_length: 512
logging_steps: 10
logging_dir: logs
